In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
engine = create_engine('postgresql://root:root@localhost:5435/ny_taxi')
engine.connect()

In [4]:
query = """
SELECT 1 as number;
"""

pd.read_sql(query, con=engine)

   number
0       1

In [6]:
query = """
SELECT *
FROM pg_catalog.pg_tables
WHERE schemaname != 'pg_catalog' AND 
    schemaname != 'information_schema';
"""

pd.read_sql(query, con=engine)

,schemaname,tablename,tableowner,tablespace,hasindexes,hasrules,hastriggers,rowsecurity
0,public,ny_taxi_data,root,None,True,False,False,False
1,public,yellow_taxi_data,root,None,True,False,False,False
2,public,zones,root,None,True,False,False,False